aashop/aashop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='myapp')),
    path('auth/', include('authentication.urls', namespace='auth')),
    path('api/v1/auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    # urlpatterns = [path('__debug__/', include('debug_toolbar.urls'))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aashop/authentication/urls.py
from django.urls import path
from authentication.views import *

app_name = 'auth'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

aashop/myapp/urls.py
from django.urls import path, include, re_path
from rest_framework import routers

from myapp.views import *

app_name = 'myapp'

routers = routers.SimpleRouter()
routers.register(r'item', ItemApiViewSet)

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', about, name='about'),
    path('add_item/', AddItem.as_view(), name='add_item'),
    path('contact/', Contacts.as_view(), name='contact'),
    path('item/<slug:slug>/', cache_page(60 * 1)(ItemDetail.as_view()), name='item_detail'),
    path('category/<int:pk>/', CategoryDetail.as_view(), name='category_detail'),
    path('search/', SearchResult.as_view(), name='search'),
    path('api/v1/', include(routers.urls)),
]

aashop/myapp/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse

from .services import calc_discont


# валидация кастомная
# def my_valid_on_7(value):
#     if "7" in value:
#         raise ValidationError('дб 7')
#     raise value
#

class ItemModelManager(models.Manager):
    def is_published(self):
        return super().get_queryset().filter(is_piblished=True)


class CommonInfo(models.Model):
    slug = models.SlugField(max_length=50, db_index=True, unique=True, verbose_name='slug')

    class Meta:
        abstract = True


class Item(CommonInfo):
    name = models.CharField(max_length=255, verbose_name='Название')
    text = models.TextField(blank=True)
    price = models.PositiveIntegerField(help_text='Цена товара')
    photo = models.ImageField(upload_to='photo', null=True)
    is_piblished = models.BooleanField(default=True)
    time_creation = models.DateField(auto_now_add=True)
    cat = models.ForeignKey('Category', on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, verbose_name='пользователь', on_delete=models.CASCADE)

    # можно брать запрос не с миксина, а с менеджера
    # objects_pub = ItemModelManager()
    def get_discount(self):
        return calc_discont(self.price, 0.2)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myapp:item_detail', kwargs={'slug': self.slug})


class Category(CommonInfo):
    title = models.CharField(max_length=255, verbose_name='категория')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('myapp:category_detail', kwargs={'pk': self.pk})

aashop/myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import TextInput

from .models import *
from django.core import validators


class ItemForm(forms.ModelForm):
    # для переопредения атрибутов
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = 'no cat'

    # наследование от модели всех полей
    class Meta:
        model = Item
        fields = ['name', 'slug', 'price', 'is_piblished', 'text', 'photo', 'cat']
        # переопределения виджетов от модели к форме
        widgets = {
            'name': TextInput(attrs={'size': 50})
        }

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

aashop/myapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from rest_framework import generics, viewsets
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, TemplateView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.authentication import BasicAuthentication, SessionAuthentication
from rest_framework.permissions import IsAuthenticatedOrReadOnly
import requests

from .models import *
from .forms import ItemForm
from .serializer import ItemSerializer
from .utils import DataMixin


class Home(DataMixin, ListView):
    model = Item
    # меняем стандартную директорию на уже имеющуюся
    template_name = 'myapp/home.html'
    # Класс вьюхи отправляет object_list, мы же меняемна items
    context_object_name = 'items'
    # так можно передать статические данные без переменных
    extra_context = {'title': 'Home'}
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        mix_cont = self.get_user_context(title='Home')
        return context | mix_cont

    # создаем запрос для отображения в шаблоне
    def get_queryset(self):
        return Item.objects.filter(is_piblished=True).select_related('cat')


# @cache_page(60 * 1)
def about(request):
    response = requests.get('https://jsonplaceholder.typicode.com/users').json()
    context = {'users': response}
    print(response)
    return render(request, 'myapp/about.html', context)


class Contacts(DataMixin, TemplateView):
    template_name = 'myapp/contact.html'

    def get_context_data(self, **kwargs):
        context = super(Contacts, self).get_context_data()
        mix_cont = self.get_user_context(title='Contact')
        return context | mix_cont


class AddItem(LoginRequiredMixin, DataMixin, CreateView):
    form_class = ItemForm
    template_name = 'myapp/add_item.html'
    context_object_name = 'form'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super(AddItem, self).get_context_data()
        mix_cont = self.get_user_context(title='ADD item')
        return context | mix_cont


class ItemDetail(DataMixin, DetailView):
    model = Item
    context_object_name = 'item'
    template_name = 'myapp/item_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ItemDetail, self).get_context_data()
        mix_cont = self.get_user_context(title=self.kwargs['slug'])
        return context | mix_cont


class CategoryDetail(DataMixin, ListView):
    model = Category
    template_name = 'myapp/category_detail.html'
    context_object_name = 'items'
    # атрибут из датамиксин
    allow_empty = False

    def get_queryset(self):
        # через кваргс можем получить значение из словоря ЗАПРОСА урла
        return Item.objects.filter(cat_id=self.kwargs['pk'], is_piblished=True).select_related('cat')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        mix_cont = self.get_user_context(title='Category - ' + str(context['items'][0].cat))
        return context | mix_cont


class SearchResult(DataMixin, ListView):
    model = Item
    template_name = 'myapp/search_result.html'
    context_object_name = 'item'

    def get_queryset(self):
        search_item = self.request.GET.get('search')
        item = Item.objects.filter(name__icontains=search_item)
        return item


class ItemApiViewSet(viewsets.ModelViewSet):
    queryset = Item.objects.all()
    serializer_class = ItemSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)
    authentication_classes = (BasicAuthentication, SessionAuthentication,)

aashop/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
	<h1>Очередной тренировочный сайт, теперь посвещен продажам.</h1>
	<p>{{ users }}</p>
{% endblock content %}

aashop/myapp/templates/myapp/add_item.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
<h1 align="center">add item</h1>
<div class="add-item">
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% for f in form %}
			<div class="form">
				<div class="form-field">
					<label for="{{ f.id_for_label }}">{{ f.label }}</label>
					{{ f }}
				</div>
			</div>

		{% endfor %}
		<button type="submit">Добавить</button>
	</form>

</div>

{% endblock content %}

aashop/myapp/templates/myapp/base.html
{% load static %}
{% load categories_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="{% static 'myapp/css/style.css' %}" type="text/css">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
		<title>
			{{ title }}
		</title>
	</head>
	<body>

		<nav class="navbar navbar-expand-lg" style="background-color: rgba(128, 0, 128, 0.5); ">
		  <div class="container-fluid">
		    <a class="navbar-brand" href="{% url 'myapp:home' %}">Home</a>
		    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		      <span class="navbar-toggler-icon"><img src="{% static '/myapp/icon/monitor.png' %}"></span>
		    </button>
		    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		      <div class="navbar-nav">
		          {% for m in menu %}
			          <a class="nav-link" href="{% url m.url %}">{{ m.title }}</a>
		          {% endfor %}
		      </div>
		      <div class="menu log-menu">
						{% if not request.user.is_authenticated %}
							<a href="{% url 'auth:login' %}">Log in</a> | <a href="{% url 'auth:register' %}">регистрация</a>
						{% else %}
							<a class="user-link" href="{% url 'auth:logout' %}">выйти</a> <div class="menu user-name">{{ user.username }}</div>
						{% endif %}
					</div>
			    <form action="{% url 'myapp:search' %}" method="get" class="d-flex" role="search">
            <input name="search" class="form-control me-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
		    </div>
		  </div>
		</nav>
			<div class="category">
<!--				{% get_cats as categories %}-->
				{% for cat in cats %}
					<h3>
						<a class="cat" href="{{ cat.get_absolute_url }}"  style="text-decoration: none; ">{{ cat.title }}</a>
					</h3>
				{% endfor %}
			</div>
		{% block content %}
		{% endblock content %}
		<div class="footer">&copy;<span id="year"> </span><span> My aashop. All rights reserved... maybe.</span></div>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
	</body>
</html>

aashop/myapp/templates/myapp/category_detail.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
{% for item in items %}
  <p>{{ item.name }}</p>
{% endfor %}
{% endblock content %}

aashop/myapp/templates/myapp/contact.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
	<h1 class="contact">123456789</h1>
{% endblock content %}

aashop/myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
<div class="item">
	{% for item in items %}
			<div class="card" style="width: 18rem; margin-bottom: 25px; margin-left: 25px;">
			  <div class="card-body">
			    <h5 class="card-title">Товар: {{ item.name }}e</h5>
			    <h6 class="card-subtitle mb-2 text-muted">Категория: {{ item.cat}}</h6>
				  <h6>cost: {{ item.price }}	&#8381;</h6>
				  <div class="link-detail">
					  <a href="{{ item.get_absolute_url }}" class="card-link-detail" style="text-decoration: none;">show detail</a>
				  </div>

			    <a href="#" class="card-link" style="text-decoration: none;">BUY</a>
			  </div>
			</div>
	{% endfor %}
</div>
<div class="paginator">
	{% if page_obj.has_previous %}
		<a class="pagin-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
	{% endif %}
	{% for page in page_obj.paginator.page_range %}
		{% if page_obj.number == page %}
			<a class="pagin-link-selected" href="?page={{ page }}">{{ page }}</a>
		{% else %}
			<a class="pagin-link" href="?page={{ page }}">{{ page }}</a>
		{% endif %}
	{% endfor %}
	{% if page_obj.has_next %}
		<a class="pagin-link" href="?page={{ page_obj.next_page_number }}">	&raquo;</a>
	{% endif %}
</div>

{% endblock content %}

aashop/myapp/templates/myapp/item_detail.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
<div class="item-detail">
  <h1>{{ item.name }}</h1>
  <h3 class="text">{{ item.text|linebreaks|truncatewords:50 }}</h3>
  {% if item.photo %}
    <p><img src="{{ item.photo.url }}" alt="photo" height="200" width="200"></p>
  {% endif %}
  <h3>Добавлено: {{ item.time_creation|date:'D d M Y' }}</h3>
  <h3><a href="#" class="card-link" style="text-decoration: none;">BUY</a></h3>
</div>

{% endblock content %}

aashop/myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
<form action="{% url 'myapp:login' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">ok</button>
</form>
{% endblock content %}

aashop/myapp/templates/myapp/search_result.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
<div class="item-detail">
  {% for i in item %}
    <h1>{{ i.name }}</h1>
    <h3 class="text">{{ i.text|linebreaks|truncatewords:50 }}</h3>
    {% if i.photo %}
      <p><img src="{{ i.photo.url }}" alt="photo" height="200" width="200"></p>
    {% endif %}
    <h3>Добавлено: {{ i.time_creation|date:'D d M Y' }}</h3>
  {% endfor %}
</div>

{% endblock content %}